version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: for-papa-backend
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_NAME=/app/data/memories.db
      - STORAGE_DIR=/app/data/storage
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: for-papa-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
